### ISSUE TITLE
Can't wait an hour for the cream

### ISSUE THREAD

**Issue by lennart-k** [Parou/Cocoa-Biscuit-Cake-with-Marshmallow-Cheese-Creme#23]
Here I am, jumping up from the couch every two minutes hoping I can finally eat this delicious cream.
A whole hour is just way too long!

**Comment by cozyplanes** [comment]
Just go to the bakery and buy one. Problem solved.

**Comment by lennart-k** [comment]
Well, they don't sell Cocoa-Biscuit-Cake-with-Marshmallow-Cheese-Creme D:<

**Comment by Parou** [comment]
I hope your cake was ready in the meantime and you were able to enjoy it.

**Comment by lennart-k** [comment]
Damn, it was so extremely delicious! :o <3
