### ISSUE TITLE
[HELP] Can't install resulting cake

### ISSUE THREAD

**Issue by ParzivalWolfram** [Parou/Cocoa-Biscuit-Cake-with-Marshmallow-Cheese-Creme#26]
my linux box is hungry but "make install" doesn't work and it needs cake badly. how do install cake into linux?

**Comment by Parou** [comment]
I am very sorry for this late reply.
Did you check that you have all the ingredients?
A free and big enough workspace?

**Comment by jonasgeiler** [comment]
lmao

**Comment by Parou** [comment]
> lmao

Hey, why are you laughing?!
This is a pretty serious topic!

**Comment by Parou** [comment]
As to demand and decision of our great @skayobot this issue will be closed.
