### ISSUE TITLE
Problems migrating to IKEA METOD

### ISSUE THREAD

**Issue by lennart-k** [Parou/Cocoa-Biscuit-Cake-with-Marshmallow-Cheese-Creme#4]
I had some problems when trying to migrate to IKEA METOD!!!!!!
FIX IT NOW!
Logs:
    "An exception occurred, please call technical support"

**Comment by Zennoe** [comment]
Could you please elaborate? Cannot reproduce

**Comment by Skayo** [comment]
Can you check your Directx Version please?
You need Directx 12 for this.

**Comment by lennart-k** [comment]
That helped, thanks

**Comment by Skayo** [comment]
No problem mate!

**Comment by Parou** [comment]
I'm glad this got solved with help of the community!
