### ISSUE TITLE
Blockchain version

### ISSUE THREAD

**Issue by lennart-k** [Parou/Cocoa-Biscuit-Cake-with-Marshmallow-Cheese-Creme#6]
We need a blockchain version!

**Comment by ir4klis** [comment]
@Parou So what are our plans on this, are we going to implement?

**Comment by lennart-k** [comment]
Oh nice, Ethereum support. <3
And I just said is as a joke 😂

**Comment by lennart-k** [comment]
This is getting crazy. :D

**Comment by ir4klis** [comment]
Well done team!
