### ISSUE TITLE
[user error] I'm to dumb for makefile cake

### ISSUE THREAD

**Issue by heyheni** [Parou/Cocoa-Biscuit-Cake-with-Marshmallow-Cheese-Creme#9]
`Makefile:10: *** missing separator.  Stop.`

I was excited and hoped for some cake magic, now this. 😢

**Comment by Parou** [comment]
@j4cobgarby

**Comment by j4cobgarby** [comment]
I'm looking into it - I haven't actually tried it yet

**Comment by Parou** [comment]
Tabs > Spaces anyways *slowly makes a step back*

**Comment by heyheni** [comment]
@j4cobgarby Fantastic it works, thank you two 😄 

`⋊> ~/D/Cocoa-Biscuit-Cake-with-Marshmallow-Cheese-Creme-master make                                                                                                                             18:37:30
mkdir -p oven clean_surface fridge microwave
echo 0 > oven/temperature
echo 0 > microwave/power
echo 0 > microwave/onoff
mkdir -p clean_surface fridge
echo 180 > oven/temperature
rm -f clean_surface/cake.tin && touch clean_surface/cake.tin
echo "Biscuit 280g" >> clean_surface/cake.tin
echo "Cocoa powder 20g" >> clean_surface/cake.tin
echo "Butter 120 g" >> clean_surface/cake.tin
mv clean_surface/cake.tin fridge
sleep 10m
mv fridge/cake.tin oven
sleep 15m
mv oven/cake.tin clean_surface
mkdir -p clean_surface
echo 600 > microwave/power
touch clean_surface/bowl
echo "Marshmallows 120g" >> clean_surface/bowl
echo "Cream Cheese 160g" >> clean_surface/bowl
mv clean_surface/bowl microwave
echo 1 > microwave/onoff
sleep 1m
ecgi 0 > microwave/onoff
/bin/sh: ecgi: command not found
make: *** [creme] Error 127`

**Comment by ParzivalWolfram** [comment]
that don't look fixed @heyheni
